Support Webvtt subtitles class colors
google/ExoPlayer pull request #4178
Opened 2018-04-24 16:19 UTC by danybony

## Problem

Colors defined in Webvtt cue Class tags were ignored.
For example in the screenshots below the cue text was
```
At the <c.red.caps>left</c> we can see...
```
Example asset: http://dash.edgesuite.net/akamai/test/caption_test/ElephantsDream/elephants_dream_480p_heaac5_1.mpd

## Solution

`WebvttCueParser` already knows about the cue classes, but these were not used. So in case of a color class, we now apply a `ForegroundColorSpan` to the subtitle text.

### Screenshots

| Before | After |
| ------ | ----- |
| ![pasted image at 2018_03_29 11_46 am](https://user-images.githubusercontent.com/3942812/38097505-dc749c5c-3375-11e8-9f82-bee682d15a0c.png) |  ![pasted image at 2018_03_29 11_43 am](https://user-images.githubusercontent.com/3942812/38097509-e0804d64-3375-11e8-95d7-4af5d83f4343.png) |

2018-04-24 16:23 UTC, danybony commented
I signed it!

2018-04-24 17:23 UTC, AquilesCanta commented
I thought VTT required the red class to be defined for the style to apply. Would you kindly provide a specification reference for this behavior change?

2018-05-09 01:23 UTC, AquilesCanta commented
Closing due to lack of activity.

2020-02-12 15:41 UTC, icbaker commented
Relevant specs:
https://www.w3.org/TR/webvtt1/#default-text-color
https://www.w3.org/TR/webvtt1/#default-text-background

Once this has a signed CLA and has been rebased/merged into current dev-v2 I can take a more in-depth look at the code.

2020-02-12 15:42 UTC, icbaker commented
I think this will likely also fix https://github.com/google/ExoPlayer/issues/6581

2020-02-12 16:21 UTC, danybony commented
I signed it!

2020-02-12 16:29 UTC, icbaker commented
@googlebot rescan

2020-02-12 16:37 UTC, icbaker commented
I can't find a record of either @danybony or dany.bony@gmail.com (the email on the commits in this PR) has signed the CLA.

Can you check what details you entered at https://cla.developers.google.com?

2020-02-12 16:39 UTC, danybony commented
Signed a newer one, just in case
![image](https://user-images.githubusercontent.com/3942812/74356474-ad9b9100-4dbe-11ea-9156-1c89d626eaae.png)

2020-02-12 16:42 UTC, icbaker commented
@googlebot rescan

2020-02-13 14:00 UTC, icbaker requested changes

2020-02-13 14:00 UTC, icbaker commented on library/core/src/main/java/com/google/android/exoplayer2/text/webvtt/WebvttCueParser.java
> +        int color = ColorParser.parseCssColor(className);
This is neat code re-use, but because the WebVTT list is so much shorter than the list of CSS colors I think it would be clearer to explicitly list the WebVTT default colors. Otherwise if someone defines a custom class called [`papayawhip`](https://www.htmlcsscolor.com/hex/FFEFD5) in their style section that maybe has nothing to do with that color, we'll color the cue anyway (which is not in-line with the WebVTT spec).

So I think a `private static final Map<String, Integer> DEFAULT_COLORS` inside `WebvttCueParser` would be the best approach here. You'll probably have to populate it in a static initializer block the same as in `ColorParser`.

That will also make adding background color support less 'different' - we can just add a `DEFAULT_BACKGROUND_COLORS` map alongside. If you have the time/inclination, feel free to also add that in this same PR! :)

2020-02-13 14:00 UTC, icbaker commented on library/core/src/main/java/com/google/android/exoplayer2/text/webvtt/WebvttCueParser.java
> +        applySupportedClasses(text, startTag.classes, start, end);
Can you add some tests to `WebvttCueParserTest` for this?

2020-02-13 14:09 UTC, danybony commented on library/core/src/main/java/com/google/android/exoplayer2/text/webvtt/WebvttCueParser.java
> +        int color = ColorParser.parseCssColor(className);
Sounds good, I'll take a look and update this soon

2020-02-13 16:38 UTC, danybony commented on library/core/src/main/java/com/google/android/exoplayer2/text/webvtt/WebvttCueParser.java
> +        int color = ColorParser.parseCssColor(className);
Updated the strategy by adding the two maps (adds support for background too) in `WebvttCueParser` and removing the dependency from the color parser.
Added relevant tests too

2020-02-13 17:44 UTC, icbaker commented
Thanks! I'll get this merged shortly.

2020-02-13 17:46 UTC, icbaker approved these changes

2020-02-17 17:10 UTC, zegnus commented
hi @icbaker what are the next steps on this PR?

2020-02-17 17:47 UTC, merged